// <auto-generated />
namespace QuanLyBanHang.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class List_Product_Category : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(List_Product_Category));
        
        string IMigrationMetadata.Id
        {
            get { return "202207281707187_List_Product_Category"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
