// <auto-generated />
namespace QuanLyBanHang.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class Init_remain_table : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Init_remain_table));
        
        string IMigrationMetadata.Id
        {
            get { return "202207271804445_Init_remain_table"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
